libs =
import libs = libimguizmo%lib{imguizmo}
import gl = libopengl-meta%lib{opengl-gl}

./: exe{example}: {hxx cxx}{**} $libs $gl

# ImApp.h is implementation, not a public header.
#
hxx{*}: install = false

out_pfx = [dir_path] $out_root/example/
src_pfx = [dir_path] $src_root/example/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"

# ImApp.h's Cocoa backend has a dead ImApp_windowShouldClose stub, superseded
# by ImApp_windowShouldClose_impl (the one actually registered).
#
if ($cxx.class == 'gcc')
  cxx.coptions += -Wno-unused-function

if ($cxx.target.class == 'windows')
{
  if ($cxx.target.system == 'mingw32')
    cxx.libs += -limm32 -lgdi32
  else
    cxx.libs += imm32.lib gdi32.lib
}
elif ($cxx.target.class == 'macos')
{
  cxx.poptions += -DGL_SILENCE_DEPRECATION
  cxx.libs += -framework Cocoa -framework Carbon -framework IOKit
}
else
{
  cxx.libs += -lX11
  if ($cxx.target.class == 'linux')
    cxx.libs += -ldl
}
