libs =
import libs = libimguizmo%lib{imguizmo}
import gl = libopengl-meta%lib{opengl-gl}

# Homebrew GCC cannot parse Apple SDK block syntax in Carbon.h.
# Upstream and cppget macOS bots use Apple Clang.
#
./: exe{example}: include = ($cxx.target.class != 'macos' || $cxx.id != 'gcc')

exe{example}: {hxx cxx}{**} $libs $gl

# ImApp.h is implementation, not a public header.
#
hxx{*}: install = false

out_pfx = [dir_path] $out_root/example/
src_pfx = [dir_path] $src_root/example/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"

if ($cxx.target.class == 'windows')
{
  if ($cxx.target.system == 'mingw32')
    cxx.libs += -limm32 -lgdi32
  else
    cxx.libs += imm32.lib gdi32.lib
}
elif ($cxx.target.class == 'macos')
{
  cxx.poptions += -DGL_SILENCE_DEPRECATION
  cxx.libs += -framework Cocoa -framework Carbon -framework IOKit
}
elif ($cxx.target.class != 'windows')
{
  cxx.libs += -lX11 -ldl
}
