intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
import intf_libs = libimgui%lib{imgui}

lib{imguizmo}: libul{imguizmo}: {hxx cxx}{**} $impl_libs $intf_libs

libs{imguizmo}: def{imguizmo}: include = ($cxx.target.system == 'win32-msvc')
def{imguizmo}: libul{imguizmo}

# Build options.
#
cxx.poptions =+ "-I$out_base" "-I$src_base"

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

# Export options.
#
lib{imguizmo}:
{
  cxx.export.poptions = "-I$out_base" "-I$src_base" "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

lib{imguizmo}: cxx.pkgconfig.include = include/ include/imguizmo/

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{imguizmo}: bin.lib.version = "-$version.project_id"
else
  lib{imguizmo}: bin.lib.version = "-$version.major.$version.minor"

# Install into the imguizmo/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
hxx{*}:
{
  install         = include/imguizmo/
  install.subdirs = true
}
